### ISSUE TITLE
Position Issue

### ISSUE THREAD

**Issue by Mert4531** [kevinatown/MMM-Screencast#53] opened 2020-01-21 09:44 UTC
Hi there;

First of all this module is so good. I have a little problem I want to change screencast window position to lower_third. However this module position settings don't have lower_third position. 
Is there any other method of setting this module to lower_third position?

**Comment by kevinatown** [comment] 2020-01-21 16:05
duplicate of #52

**Closed by kevinatown** 2020-01-21 16:05 UTC
