### ISSUE TITLE
Utube URL

### ISSUE THREAD

**Issue by manojjenago** [kevinatown/MMM-Screencast#8] opened 2018-01-27 05:28 UTC
Hi Kevin,
Thanks for a wonderful app. It's really nice. However my videos are buffering too much when I cast on TV. And also if I enlarge then the problem is bigger. Please suggest. 
What I was thinking is there anyway we can play the video URL in OMXplayer.
1-First grab the URL from youtube from the phone 
2-Send pi to open this in OMXPlayer.

Just a thought . May be you can guide. The URL looks like you are opening in (www.youtube.com/tv) and when I take the URL and paste on the browser it goes to main page not to the particular video. Please let me know how I can get the particular video URL from this app??
Thanks again for such a wonderful extension to MagicMirror....
MKJ

**Comment by kevinatown** [comment] 2018-02-15 22:29
Hey MKJ. So originally I was stealing the video tag from the cast and opening the video in in a new window with a standard youtube `watch?v=` the issue with doing it this way was that you didnt have full control over the video (e.g. stop, play, volume, etc). That's why I had to switch to using the `youtube.com/tv` app. It's something that was created youtube to handle DIAL, which I believe has been replaced by mDNS. All of this to say is that at this point I am unsure if there is away to improve the streaming quality of the app. I want to spend more time looking into using mDNS, but I'd have to do more research.

**Comment by kevinatown** [comment] 2018-02-15 22:33
Your comment on the other issue:
```
Hi kevin,

I want to get the URL like Iphone provides
( electron app.js "http://www.youtube.com/tv?pairingCode=BF5A6013-8AB5-47DD-A820-018A6E2C566F&rUrl=ws%3A%2F%2F192.168.1.9%3A57364%2FD214526C-AEE8-4E7E-8100-8AAA59226DEE&rId=C641178A-655D-41CE-9FBC-8BC16A9C1008&t=7.1&theme=cl&v=BAYOqpNbFeo" ) in Android (Nexus) But the URL looks different and does not have the v="" which I believe the ID of the Video ... how it plays in OMXPlayer from android then ??
```

**Comment by kevinatown** [comment] 2018-02-15 22:35
So the issue is that you need to parse everything after the `youtube.com/tv?`, if you notice the last parameter is the video tag: `v=BAYOqpNbFeo`.

**Comment by manojjenago** [comment] 2018-03-22 17:06
thanks

Thanks,
Manoj

**Comment by kevinatown** [comment] 2018-03-25 01:39
Im going to close this issue. Feel free to open another one if you have any more problems.

**Closed by kevinatown** 2018-03-25 01:39 UTC

**Comment by radokristof** [comment] 2020-06-18 18:15
@kevinatown Did you thought about moving to mDNS?
All of the current Google devices (Google Home, Google Chromecast) uses mDNS instead of DIAL (and almost every IoT device use this). I don't know if it is possible to implement this but it would be great, mainly because I did not find a great way to route DIAL (SSDP and UPnP) between networks. This is needed for me cause I have a different network for IoT devices.
Maybe this can help:
https://github.com/jloutsenhizer/CR-Cast/wiki/Chromecast-Implementation-Documentation-WIP#dialssdp
