### ISSUE TITLE
Casting different formats QUESTION

### ISSUE THREAD

**Issue by Bernard-h** [kevinatown/MMM-Screencast#61] opened 2020-03-12 10:08 UTC
Would it be difficult to get this working on Netflix / Ziggo / HBO / Disney ?

**Comment by kevinatown** [comment] 2020-05-29 13:15
So sadly it's not trivial. I've spent sometime looking into netflix but have yet to have gotten it to work and then work, life, other projects come up and i loose track of where I was. I'll try to find time to open this up again.

Also I'm going to close this ticket as it's a duplicate of #27

**Closed by kevinatown** 2020-05-29 13:15 UTC
